### ISSUE TITLE
WHO ARE YOU???

### ISSUE THREAD

**Issue by spfng** [tsaop/crux-kf5#10]
HOW???

How you can maintain KDE5 in solo???? DUDE! Its impossible!!!

I have using CRUX since 2011 and I have no time to maintain a few small ports.

YOU MAINTAIN KDE5!!!!

HOW!!??????

**Comment by tsaop** [comment]
It's not much work actually...
When frameworks / plasma / applications get released I update them in bulk with a for loop and then fix breakage due to new dependencies / deprecations.

Also "maintain" is a big word. Currently I simply push a port once it builds, no testing done.

**Comment by spfng** [comment]
> It's not much work actually... When frameworks / plasma / applications get released I update them in bulk with a for loop and then fix breakage due to new dependencies / deprecations.
> 
> Also "maintain" is a big word. Currently I simply push a port once it builds, no testing done.

Awesome! Dude! Thank you a lot for your job!!!
