### ISSUE TITLE
kio-extras is missing a (new?) dependency: kdsoap

### ISSUE THREAD

**Issue by mhoush** [tsaop/crux-kf5#12]
Greetings! Ran into a missing dependency when building recently, looks like kio-extras now needs kdsoap. Here's an example Pkgfile (sans headers) if it's helpful, feel free to tweak as needed:

```
name=kdsoap
version=2.1.1
release=1
source=(https://github.com/KDAB/KDSoap/releases/download/$name-$version/$name-$version.tar.gz)

build() {
        cd $name-$version

        cmake \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=/usr/lib \
                -DKDSoap_EXAMPLES=false \
                -DCMAKE_BUILD_TYPE=Release

        make
        make DESTDIR=$PKG install

        rm -r $PKG/usr/share/doc
}
```

**Comment by tsaop** [comment]
Hello, I added the missing kdsoap and kdsoap-ws-discovery-client ports.
Also, i have bumped the release on kio-extras to force a rebuild.

Please test and let me know if it works.

Thanks.

**Comment by mhoush** [comment]
Looks like it works fine here. Thanks!
