### ISSUE TITLE
qcoro prefers qt6

### ISSUE THREAD

**Issue by TimB87** [tsaop/crux-kf5#16]
If both is present on the building system, it prefers qt6 and does not build qt5 libraries resulting in a footprint mismatch:

Footprint mismatch: https://dpaste.org/hibxm

Adding `-DUSE_QT_VERSION=5` forces it to build the correct version.
I propose a rename to qcoro-qt5 or similiar to be prepared for whenever we might need a qcoro-qt6? :)

**Comment by tsaop** [comment]
Should be fixed now. I've renamed qcoro to qcoro-qt5
