### ISSUE TITLE
qt5.10 update breaks krunner

### ISSUE THREAD

**Issue by timcowchip** [tsaop/crux-kf5#3]
I'm just guessing that the latest update to qt5.10 broke krunner. I had previously installed kf5 with qt5.9 and it worked fine, but when I tried "prt-get depinst frameworks-meta plasma-meta applications-meta --install-scripts" after updating qt5, it stopped at building krunner.

[ 96%] Linking CXX executable ../bin/testremoterunner
/usr/lib64/libKF5Declarative.so.5: undefined reference to `QQmlPropertyMap::init(QMetaObject const*)@Qt_5'
/usr/lib64/libKF5Declarative.so.5: undefined reference to `QQmlPropertyMap::allocatePrivate()@Qt_5'
collect2: error: ld returned 1 exit status
make[2]: *** [autotests/CMakeFiles/testremoterunner.dir/build.make:159: bin/testremoterunner] Error 1
make[1]: *** [CMakeFiles/Makefile2:437: autotests/CMakeFiles/testremoterunner.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
=======> ERROR: Building '/usr/ports/kf5/krunner/krunner#5.41.0-1.pkg.tar.gz' failed.

**Comment by therealromster** [comment]
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/usr/ports/kf5/libdbusmenu-qt5/work/src/libdbusmenu-qt-0.9.3+16.04.20160218/CMakeFiles/CMakeOutput.log".
=======> ERROR: Building '/usr/ports/kf5/libdbusmenu-qt5/libdbusmenu-qt5#0.9.3+16.04.20160218-1.pkg.tar.xz' failed.
prt-get: error while install

missing qt5 on # Depends on:


=======> ERROR: Footprint mismatch found:
MISSING   drwxr-xr-x      root/root       usr/include/dbusmenu-qt5/CMakeFiles/dbusmenu-qt5_automoc.dir/
NEW       drwxr-xr-x      root/root       usr/include/dbusmenu-qt5/CMakeFiles/dbusmenu-qt5.dir/dbusmenu-qt5_autogen/
NEW       drwxr-xr-x      root/root       usr/include/dbusmenu-qt5/CMakeFiles/dbusmenu-qt5_autogen.dir/
NEW       drwxr-xr-x      root/root       usr/include/dbusmenu-qt5/dbusmenu-qt5_autogen/
NEW       drwxr-xr-x      root/root       usr/include/dbusmenu-qt5/dbusmenu-qt5_autogen/include/
NEW       -rw-r--r--      root/root       usr/include/dbusmenu-qt5/dbusmenu-qt5_autogen/moc_predefs.h
=======> ERROR: Building '/usr/ports/kf5/libdbusmenu-qt5/libdbusmenu-qt5#0.9.3+16.04.20160218-1.pkg.tar.xz' failed.

=======> Building '/usr/ports/kf5/krunner/krunner#5.41.0-1.pkg.tar.xz' succeeded.
prt-get: installing krunner 5.41.0-1

-- Packages installed
attica
kconfig
kcoreaddons
kwindowsystem
kdbusaddons
kwidgetsaddons
polkit-qt5
kcodecs
karchive
ki18n
kguiaddons
kitemviews
sonnet
gpgme-qt5
phonon-qt5
solid
kwayland
threadweaver
kcrash
kcompletion
kjobwidgets
kauth
kdoctools
knotifications
kglobalaccel
kconfigwidgets
kservice
kpackage
kiconthemes
ktextwidgets
kwallet
kxmlgui
kbookmarks
kio [post: ok]
kactivities
kdeclarative
plasma-framework
krunner

prt-get: installed successfully


Did you run revdep?

**Comment by timcowchip** [comment]
I did run revdep and it showed nothing. I had to upgrade QupZilla from 2.2.1 to 2.2.3 to get it to work with qt5 and revdep didn't report QupZilla as broken either. I rebuilt kdeclarative and krunner builds successfully.

**Comment by tsaop** [comment]
libdbusmenu-qt5 depends on qjson which in turn depends on qt5, so it should all work there.
