### ISSUE TITLE
FYI: contrib/quazip5

### ISSUE THREAD

**Issue by TimB87** [tsaop/crux-kf5#6]
Hi @tsaop 
I didn't check with you or kde5 repo.. but in case you didn't notice there is contrib/quazip5 now that you can depend on.

Best regards
Tim

**Comment by tsaop** [comment]
Hello,
I have removed quazip from my repo and defaulted to quazip5 in contrib (see a0134127b2facd60ec4943a9b8b4e4b1d66f924b)

Thanks for the tip.

**Comment by TimB87** [comment]
No problem
