### ISSUE TITLE
libproxy was removed from official repos

### ISSUE THREAD

**Issue by TimB87** [tsaop/crux-kf5#8]
Hi tsaop!

Sorry to inform you that libproxy was removed from official repos during a clean up of leftover ports from past maintainers.

From #crux on freenode..
```
19:14 < brian|lfs> libproxy is pretty common shocked it was removed from contrib
19:19 < beerman> brian|lfs: maintain it :)
19:27 < brian|lfs> well I could tell tsaop no one is maintaing it that plasma is broken without it lol
19:27 < beerman> would be pretty open source thinking of you
20:38 < brian|lfs> is anyone running plasma from tsaop
20:39 < brian|lfs> from what I can see its all compiled but it won't start and not seeing any error messages
```

Sorry that @bmadonnaster wanted to report it but still didn't..

It might be possible that more will go or others are affected, the clean up is not completely done and I hope for other maintainers to grab some stuff or new maintainers that will apply to contrib to keep stuff living.

Let me know if I can help.
Best regards,
Tim

**Comment by tsaop** [comment]
Hello,

for the moment I have included the libproxy port in this repo.
Let me know if we can reinclude it in contrib.

**Comment by TimB87** [comment]
Nothing in contrib depended on libproxy which was the number one reason to have it removed.
I am currently not seeking to adopt many more ports for the sake of "somebody got to do it", so the best chance I see is either staying contrib members that want to take the port over or a new maintainer would join contrib and bring it along.

Have you ever thought about joining?
